"""add_time_tracking_and_risk_models

Revision ID: 0e47266203f9
Revises: f1e2d3c4b5a6
Create Date: 2026-05-07 03:04:23.287576

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e47266203f9"
down_revision: Union[str, None] = "f1e2d3c4b5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_snapshot",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("risk_score", sa.Float(), nullable=False),
        sa.Column("risk_level", sa.String(length=20), nullable=False),
        sa.Column("signals", sa.JSON(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("predicted_completion_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alert_sent", sa.Boolean(), nullable=False),
        sa.Column("alert_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("actual_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("prediction_error_hours", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_checkpoint",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("reported_by", sa.String(length=36), nullable=False),
        sa.Column("progress_pct", sa.Integer(), nullable=False),
        sa.Column("is_blocked", sa.Boolean(), nullable=False),
        sa.Column("blocked_reason", sa.String(length=500), nullable=True),
        sa.Column("remaining_hours", sa.Float(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["reported_by"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_time_log",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("log_type", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("logged_date", sa.Date(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "event", sa.Column("event_category", sa.String(length=50), nullable=True)
    )
    op.drop_constraint(op.f("event_task_id_fkey"), "event", type_="foreignkey")
    op.create_foreign_key(None, "event", "task", ["task_id"], ["id"])
    op.add_column("task", sa.Column("estimated_hours", sa.Float(), nullable=True))
    op.add_column(
        "task",
        sa.Column("actual_hours", sa.Float(), nullable=False, server_default="0"),
    )
    op.drop_constraint(op.f("task_assignee_id_fkey"), "task", type_="foreignkey")
    op.drop_column("task", "assignee_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "assignee_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("task_assignee_id_fkey"), "task", "project_member", ["assignee_id"], ["id"]
    )
    op.drop_column("task", "actual_hours")
    op.drop_column("task", "estimated_hours")
    op.drop_constraint(None, "event", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_task_id_fkey"),
        "event",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("event", "event_category")
    op.drop_table("task_time_log")
    op.drop_table("task_checkpoint")
    op.drop_table("risk_snapshot")
    # ### end Alembic commands ###
