"""add task_activity

Revision ID: 1299fba30b45
Revises: f1e2d3c4b5a6
Create Date: 2026-05-08 06:13:40.676723

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1299fba30b45"
down_revision: Union[str, None] = "f1e2d3c4b5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_activity",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("field_changed", sa.String(length=50), nullable=False),
        sa.Column("old_value", sa.String(length=255), nullable=True),
        sa.Column("new_value", sa.String(length=255), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_task_activity_task_id"), "task_activity", ["task_id"], unique=False
    )
    op.execute("ALTER TABLE event DROP CONSTRAINT IF EXISTS event_task_id_fkey")
    op.execute("ALTER TABLE task DROP CONSTRAINT IF EXISTS task_assignee_id_fkey")
    op.execute("ALTER TABLE task DROP COLUMN IF EXISTS assignee_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "assignee_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("task_assignee_id_fkey"), "task", "project_member", ["assignee_id"], ["id"]
    )
    op.add_column(
        "event",
        sa.Column("task_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("event_task_id_fkey"),
        "event",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_task_activity_task_id"), table_name="task_activity")
    op.drop_table("task_activity")
    # ### end Alembic commands ###
