"""refactor_task_system_for_deadline_model

Revision ID: 56631e2717e5
Revises: 7aa8a735637d
Create Date: 2026-05-11 15:10:59.715898

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56631e2717e5"
down_revision: Union[str, None] = "7aa8a735637d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_member",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["task_id"], ["task.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("task_assignee")
    op.add_column(
        "task", sa.Column("started_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "task", sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("task_assigner_id_fkey"), "task", type_="foreignkey")
    op.drop_column("task", "start_date")
    op.drop_column("task", "assigner_id")
    op.add_column(
        "task_activity",
        sa.Column(
            "activity_type",
            sa.String(length=30),
            nullable=False,
            server_default="field_change",
        ),
    )
    op.add_column(
        "task_activity", sa.Column("field_name", sa.String(length=50), nullable=True)
    )
    op.add_column("task_activity", sa.Column("content", sa.Text(), nullable=True))
    op.add_column(
        "task_activity",
        sa.Column(
            "is_edited", sa.Boolean(), nullable=False, server_default=sa.text("false")
        ),
    )
    op.add_column(
        "task_activity",
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "task_activity",
        sa.Column(
            "mentioned_user_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.alter_column(
        "task_activity",
        "old_value",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "task_activity",
        "new_value",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.drop_column("task_activity", "field_changed")
    op.add_column(
        "task_checkpoint",
        sa.Column(
            "checkpoint_type",
            sa.String(length=30),
            nullable=False,
            server_default="progress",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_checkpoint", "checkpoint_type")
    op.add_column(
        "task_activity",
        sa.Column(
            "field_changed", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
    )
    op.alter_column(
        "task_activity",
        "new_value",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.alter_column(
        "task_activity",
        "old_value",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.drop_column("task_activity", "mentioned_user_ids")
    op.drop_column("task_activity", "edited_at")
    op.drop_column("task_activity", "is_edited")
    op.drop_column("task_activity", "content")
    op.drop_column("task_activity", "field_name")
    op.drop_column("task_activity", "activity_type")
    op.add_column(
        "task",
        sa.Column(
            "assigner_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("task_assigner_id_fkey"), "task", "project_member", ["assigner_id"], ["id"]
    )
    op.drop_column("task", "completed_at")
    op.drop_column("task", "started_at")
    op.create_table(
        "task_assignee",
        sa.Column(
            "task_id", sa.VARCHAR(length=36), autoincrement=False, nullable=False
        ),
        sa.Column(
            "project_member_id",
            sa.VARCHAR(length=36),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_member_id"],
            ["project_member.id"],
            name=op.f("task_assignee_project_member_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
            name=op.f("task_assignee_task_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "task_id", "project_member_id", name=op.f("task_assignee_pkey")
        ),
    )
    op.drop_table("task_member")
    # ### end Alembic commands ###
