"""add team_id to notification

Revision ID: 5ececf1c1943
Revises: f1e2d3c4b5a6
Create Date: 2026-05-07 13:25:48.451278

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5ececf1c1943"
down_revision: Union[str, None] = "f1e2d3c4b5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notification", sa.Column("team_id", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_notification_team_id"), "notification", ["team_id"], unique=False
    )
    op.create_foreign_key(None, "notification", "team", ["team_id"], ["id"])
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "assignee_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("task_assignee_id_fkey"), "task", "project_member", ["assignee_id"], ["id"]
    )
    op.drop_constraint(None, "notification", type_="foreignkey")
    op.drop_index(op.f("ix_notification_team_id"), table_name="notification")
    op.drop_column("notification", "team_id")
    op.add_column(
        "event",
        sa.Column("task_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("event_task_id_fkey"),
        "event",
        "task",
        ["task_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
