"""create notification table

Revision ID: 79adb4a15d9e
Revises: b395aa60c9a7
Create Date: 2026-05-01 15:05:13.062495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79adb4a15d9e'
down_revision: Union[str, None] = 'b395aa60c9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enums first
    notification_type = sa.Enum('SYSTEM', 'INVITATION', 'TASK_ASSIGNED', 'PROJECT_UPDATE', name='notificationtype')
    notification_status = sa.Enum('ACTIVE', 'ARCHIVED', name='notificationstatus')

    op.create_table('notification',
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.String(length=36), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('content', sa.String(length=1000), nullable=True),
        sa.Column('type', notification_type, nullable=False),
        sa.Column('status', notification_status, nullable=False),
        sa.Column('is_read', sa.Boolean(), nullable=False, server_default='false'),
        sa.Column('resource_id', sa.String(length=36), nullable=True),
        sa.Column('resource_type', sa.String(length=50), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    # Drop enums
    sa.Enum(name='notificationtype').drop(op.get_bind())
    sa.Enum(name='notificationstatus').drop(op.get_bind())
    # ### end Alembic commands ###
