"""create notification table

Revision ID: 79adb4a15d9e
Revises: b395aa60c9a7
Create Date: 2026-05-01 15:05:13.062495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79adb4a15d9e'
down_revision: Union[str, None] = 'b395aa60c9a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('data', sa.JSON(), nullable=True))
    op.alter_column('notification', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'content',
               existing_type=sa.VARCHAR(length=1000),
               nullable=False)
    op.drop_column('notification', 'data')
    # ### end Alembic commands ###
