"""add_timezone_to_project

Revision ID: 7aa8a735637d
Revises: 1c75f1334ccd
Create Date: 2026-05-09 06:00:50.707399

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7aa8a735637d"
down_revision: Union[str, None] = "1c75f1334ccd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "event", "task", ["task_id"], ["id"])
    op.drop_index(op.f("ix_notification_team_id"), table_name="notification")
    op.drop_column("notification", "team_id")
    op.add_column(
        "project",
        sa.Column(
            "timezone",
            sa.String(length=50),
            nullable=False,
            server_default="Asia/Ho_Chi_Minh",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "timezone")
    op.add_column(
        "notification",
        sa.Column("team_id", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.create_index(
        op.f("ix_notification_team_id"), "notification", ["team_id"], unique=False
    )
    op.drop_constraint(None, "event", type_="foreignkey")
    # ### end Alembic commands ###
