"""add_team_id_to_notification

Revision ID: adbae1aba004
Revises: 5ececf1c1943
Create Date: 2026-05-07 14:28:06.265290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adbae1aba004'
down_revision: Union[str, None] = '5ececf1c1943'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notification_team_id_fkey'), 'notification', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('notification_team_id_fkey'), 'notification', 'team', ['team_id'], ['id'])
    # ### end Alembic commands ###
